name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Lint changed files (PR or Push)
        run: |
          echo "Event: $GITHUB_EVENT_NAME"

          if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
            echo "Detected Pull Request — comparing with base branch"
            git fetch origin ${{ github.base_ref }}
            BASE_REF="origin/${{ github.base_ref }}"
          else
            echo "Detected Direct Push — comparing with previous commit"
            BASE_REF="HEAD^"
          fi

          echo "Comparing changes from $BASE_REF to HEAD"

          # Get changed JS/TS files and filter out deleted ones
          mapfile -t CHANGED_FILES < <(git diff --name-only "$BASE_REF" HEAD -- '*.js' '*.ts' '*.tsx' '*.jsx')

          EXISTING_FILES=()
          for file in "${CHANGED_FILES[@]}"; do
            if [ -f "$file" ]; then
              EXISTING_FILES+=("$file")
            fi
          done

          if [ ${#EXISTING_FILES[@]} -eq 0 ]; then
            echo "No JS/TS files to lint."
            exit 0
          fi

          echo "Linting the following files:"
          printf '%s\n' "${EXISTING_FILES[@]}"

          npx eslint "${EXISTING_FILES[@]}"
